# Generated by Django 5.0.2 on 2024-03-10 18:28

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        ("images", "0002_alter_customimage_caption"),
        ("wagtailcore", "0092_query_searchpromotion_querydailyhits"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=100)),
                ("county", models.CharField(blank=True, max_length=100)),
                (
                    "state",
                    models.CharField(blank=True, default="Illinois", max_length=20),
                ),
                ("special_features", models.TextField(blank=True)),
                ("project_dimensions", models.CharField(blank=True, max_length=100)),
                ("sales_person", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField()),
                ("review", wagtail.fields.RichTextField(blank=True)),
                (
                    "project_hero",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ProjectsCategoryPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("details", models.TextField(blank=True)),
                (
                    "category_brochure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="documents.customdocument",
                    ),
                ),
                (
                    "subcategory_hero",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Category",
                "verbose_name_plural": "Projects Categories",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ProjectsIndex",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "category_hero",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Projects",
                "verbose_name_plural": "Projects",
            },
            bases=("wagtailcore.page",),
        ),
    ]
