# Generated by Django 5.0.2 on 2024-03-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_projectpagetags_projectpage_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectpage",
            name="subtitle",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
