# Generated by Django 5.0.2 on 2024-03-10 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0002_alter_customimage_caption"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staffindex",
            name="category_hero",
        ),
        migrations.AddField(
            model_name="staffindex",
            name="staff_hero",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
            ),
        ),
    ]
