# Generated by Django 5.0.2 on 2024-03-10 20:15

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0002_alter_customimage_caption"),
        ("staff", "0003_staffindex_subtitle"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffpage",
            name="bio",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="staffpage",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="staffpage",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="staffpage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
            ),
        ),
        migrations.AddField(
            model_name="staffpage",
            name="job_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="staffpage",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="staffpage",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
