# Generated by Django 5.0.2 on 2024-03-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0004_staffpage_bio_staffpage_email_staffpage_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffpage",
            name="job_title",
            field=models.CharField(
                blank=True,
                choices=[
                    ("owner", "Owner / CEO"),
                    ("office", "Office Staff"),
                    ("sales", "Sales"),
                    ("project_manager", "Project Manager"),
                ],
                max_length=255,
            ),
        ),
    ]
