# Generated by Django 5.0.2 on 2024-03-01 16:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogindex",
            options={
                "verbose_name": "Blog Landing Page",
                "verbose_name_plural": "Blog Landing Pages",
            },
        ),
    ]
