# Generated by Django 5.0.2 on 2024-03-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_remove_blogdetail_hero_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogdetail",
            name="author",
            field=models.ManyToManyField(
                blank=True, related_name="blog_posts", to="blog.author"
            ),
        ),
    ]
