# Generated by Django 5.0.2 on 2024-03-01 21:10

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_blogdetail_hero_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogindex",
            name="body",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="This text will appear on the blog landing page"
            ),
        ),
    ]
