# Generated by Django 5.0.2 on 2024-03-16 00:22

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.snippets.blocks
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_alter_blogdetail_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogdetail",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "author",
                        wagtail.snippets.blocks.SnippetChooserBlock("blog.Author"),
                    ),
                    (
                        "hero",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image_desktop",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        help_text="Image needs to be landscape 2560-w x1400-h pixels."
                                    ),
                                ),
                                (
                                    "image_mobile",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        help_text="Image needs to be portraits 800w x 1,200h pixels."
                                    ),
                                ),
                                ("title", wagtail.blocks.CharBlock()),
                                ("text", wagtail.blocks.TextBlock()),
                                ("button", wagtail.blocks.CharBlock()),
                                (
                                    "page_chooser",
                                    wagtail.blocks.PageChooserBlock(required=False),
                                ),
                            ]
                        ),
                    ),
                    (
                        "carousel",
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    "slide",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "image_desktop",
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    help_text="Image needs to be landscape 2560-w x1400-h pixels."
                                                ),
                                            ),
                                            (
                                                "image_mobile",
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    help_text="Image needs to be portraits 800w x 1,200-h pixels."
                                                ),
                                            ),
                                            ("title", wagtail.blocks.CharBlock()),
                                            ("text", wagtail.blocks.TextBlock()),
                                            ("button", wagtail.blocks.CharBlock()),
                                            (
                                                "page_chooser",
                                                wagtail.blocks.PageChooserBlock(
                                                    required=False
                                                ),
                                            ),
                                        ]
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "text",
                        wagtail.blocks.StructBlock(
                            [("text", wagtail.blocks.TextBlock())]
                        ),
                    ),
                    (
                        "paragraph",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "RichText",
                                    wagtail.blocks.RichTextBlock(
                                        features=[
                                            "h2",
                                            "h3",
                                            "bold",
                                            "italic",
                                            "ol",
                                            "ul",
                                            "link",
                                            "blockquote",
                                        ]
                                    ),
                                )
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                verbose_name="Body Content",
            ),
        ),
    ]
