# Generated by Django 5.0.2 on 2024-03-16 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0012_alter_blogdetail_body"),
        ("images", "0002_alter_customimage_caption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogdetail",
            name="hero_image_desktop",
            field=models.ForeignKey(
                blank=True,
                help_text="Image needs to be landscape 2560-w x1400-h pixels.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
            ),
        ),
    ]
