# Generated by Django 5.0.2 on 2024-03-02 03:50

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
        ("home", "0002_create_homepage"),
        ("images", "0001_initial"),
        ("wagtailcore", "0092_query_searchpromotion_querydailyhits"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="cta_external_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="cta_link_name",
            field=models.CharField(default="Learn More", max_length=100),
        ),
        migrations.AddField(
            model_name="homepage",
            name="cta_url",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="custom_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="documents.customdocument",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="subtitle",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
