# Generated by Django 5.0.2 on 2024-03-15 18:16

import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("text", wagtail.blocks.TextBlock()),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    (
                        "carousel",
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    "slide",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "image",
                                                wagtail.images.blocks.ImageChooserBlock(),
                                            ),
                                            ("title", wagtail.blocks.CharBlock()),
                                            ("text", wagtail.blocks.TextBlock()),
                                            ("button", wagtail.blocks.CharBlock()),
                                            (
                                                "page_chooser",
                                                wagtail.blocks.PageChooserBlock(
                                                    required=False
                                                ),
                                            ),
                                        ]
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "hero",
                        wagtail.blocks.StructBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                ("title", wagtail.blocks.CharBlock()),
                                ("text", wagtail.blocks.TextBlock()),
                                ("button", wagtail.blocks.CharBlock()),
                                (
                                    "page_chooser",
                                    wagtail.blocks.PageChooserBlock(required=False),
                                ),
                            ]
                        ),
                    ),
                    (
                        "video",
                        wagtail.blocks.StructBlock(
                            [("video", wagtail.embeds.blocks.EmbedBlock())]
                        ),
                    ),
                ],
                blank=True,
                null=True,
            ),
        ),
    ]
