# Generated by Django 5.0.2 on 2024-03-16 12:39

import blocks.blocks
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "rich_text",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "RichText",
                                    wagtail.blocks.RichTextBlock(
                                        features=[
                                            "h2",
                                            "h3",
                                            "bold",
                                            "italic",
                                            "ol",
                                            "ul",
                                            "link",
                                            "blockquote",
                                        ]
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "carousel",
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    "slide",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "image_desktop",
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    help_text="Image needs to be landscape 2560-w x 1400-h pixels."
                                                ),
                                            ),
                                            (
                                                "image_mobile",
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    help_text="Image needs to be portraits 800-w x 1,200-h pixels."
                                                ),
                                            ),
                                            ("title", wagtail.blocks.CharBlock()),
                                            ("text", wagtail.blocks.TextBlock()),
                                            ("button", wagtail.blocks.CharBlock()),
                                            (
                                                "page_chooser",
                                                wagtail.blocks.PageChooserBlock(
                                                    required=False
                                                ),
                                            ),
                                        ]
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "hero",
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    "hero",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "image_desktop",
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    help_text="Image needs to be landscape 2560-w x 1400-h pixels."
                                                ),
                                            ),
                                            (
                                                "image_mobile",
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    help_text="Image needs to be portraits 800w x 1,200h pixels."
                                                ),
                                            ),
                                            ("title", wagtail.blocks.CharBlock()),
                                            ("text", wagtail.blocks.TextBlock()),
                                            ("button", wagtail.blocks.CharBlock()),
                                            (
                                                "page_chooser",
                                                wagtail.blocks.PageChooserBlock(
                                                    required=False
                                                ),
                                            ),
                                        ]
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "video",
                        wagtail.blocks.StructBlock(
                            [("video", wagtail.embeds.blocks.EmbedBlock())]
                        ),
                    ),
                    ("text", blocks.blocks.TextBlock()),
                ],
                blank=True,
                null=True,
            ),
        ),
    ]
