# Generated by Django 5.0.2 on 2024-03-10 15:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0002_alter_customimage_caption"),
        ("products", "0001_initial"),
        ("wagtailcore", "0092_query_searchpromotion_querydailyhits"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SubcategoryPage",
            new_name="ProductsCategoryPage",
        ),
        migrations.RenameModel(
            old_name="CategoryPage",
            new_name="ProductsIndex",
        ),
    ]
