# Generated by Django 5.0.2 on 2024-03-10 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
        ("products", "0002_rename_subcategorypage_productscategorypage_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productpage",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
        migrations.AlterModelOptions(
            name="productscategorypage",
            options={
                "verbose_name": "Product Category",
                "verbose_name_plural": "Products Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="productsindex",
            options={"verbose_name": "Products", "verbose_name_plural": "Products"},
        ),
        migrations.AddField(
            model_name="productpage",
            name="brochure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="documents.customdocument",
            ),
        ),
        migrations.AddField(
            model_name="productscategorypage",
            name="category_brochure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="documents.customdocument",
            ),
        ),
    ]
