# Generated by Django 5.0.2 on 2024-03-15 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0002_alter_customimage_caption"),
        ("products", "0003_alter_productpage_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productpage",
            name="product_hero",
        ),
        migrations.AddField(
            model_name="productpage",
            name="product_hero_desktop",
            field=models.ForeignKey(
                blank=True,
                help_text="Image needs to be landscape 1920w x1080h pixels.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
            ),
        ),
        migrations.AddField(
            model_name="productpage",
            name="product_hero_mobile",
            field=models.ForeignKey(
                blank=True,
                help_text="Image needs to be portraits 800w x 1,200h pixels.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
            ),
        ),
    ]
