# Generated by Django 5.0.2 on 2024-03-16 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0002_alter_customimage_caption"),
        ("products", "0006_productpagegalleryimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productpagegalleryimage",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="images.customimage",
            ),
        ),
    ]
